package com.iss.db.bean;

import java.util.Set;

// Generated 2017-2-21 11:35:18 by Hibernate Tools 4.3.5.Final

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer id;
	private String deptName;
	private Integer parentId;
	private String desc;
	private Byte enable;
	
	private Set<Department>children;
	public Set<Department> getChildren(){
		return children;
		
	}
	public void setChildren(Set<Department> children){
		this.children=children;
	}

	public Department() {
	}

	public Department(String deptName) {
		this.deptName = deptName;
	}
	public String getText(){
		
		return this.deptName;
	}

	public Department(String deptName, Integer parentId, String desc, Byte enable) {
		this.deptName = deptName;
		this.parentId = parentId;
		this.desc = desc;
		this.enable = enable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Byte getEnable() {
		return this.enable;
	}

	public void setEnable(Byte enable) {
		this.enable = enable;
	}

}
