package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Deptview generated by hbm2java
 */
public class Deptview implements java.io.Serializable {

	private DeptviewId id;

	public Deptview() {
	}

	public Deptview(DeptviewId id) {
		this.id = id;
	}

	public DeptviewId getId() {
		return this.id;
	}

	public void setId(DeptviewId id) {
		this.id = id;
	}

}
