package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * DeptviewId generated by hbm2java
 */
public class DeptviewId implements java.io.Serializable {

	private int id;
	private String deptName;
	private Integer parentId;
	private String deptParent;
	private String desc;
	private Byte enable;

	public DeptviewId() {
	}

	public DeptviewId(int id, String deptName) {
		this.id = id;
		this.deptName = deptName;
	}

	public DeptviewId(int id, String deptName, Integer parentId, String deptParent, String desc, Byte enable) {
		this.id = id;
		this.deptName = deptName;
		this.parentId = parentId;
		this.deptParent = deptParent;
		this.desc = desc;
		this.enable = enable;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getDeptParent() {
		return this.deptParent;
	}

	public void setDeptParent(String deptParent) {
		this.deptParent = deptParent;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Byte getEnable() {
		return this.enable;
	}

	public void setEnable(Byte enable) {
		this.enable = enable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptviewId))
			return false;
		DeptviewId castOther = (DeptviewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDeptName() == castOther.getDeptName()) || (this.getDeptName() != null
						&& castOther.getDeptName() != null && this.getDeptName().equals(castOther.getDeptName())))
				&& ((this.getParentId() == castOther.getParentId()) || (this.getParentId() != null
						&& castOther.getParentId() != null && this.getParentId().equals(castOther.getParentId())))
				&& ((this.getDeptParent() == castOther.getDeptParent()) || (this.getDeptParent() != null
						&& castOther.getDeptParent() != null && this.getDeptParent().equals(castOther.getDeptParent())))
				&& ((this.getDesc() == castOther.getDesc()) || (this.getDesc() != null && castOther.getDesc() != null
						&& this.getDesc().equals(castOther.getDesc())))
				&& ((this.getEnable() == castOther.getEnable()) || (this.getEnable() != null
						&& castOther.getEnable() != null && this.getEnable().equals(castOther.getEnable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getDeptName() == null ? 0 : this.getDeptName().hashCode());
		result = 37 * result + (getParentId() == null ? 0 : this.getParentId().hashCode());
		result = 37 * result + (getDeptParent() == null ? 0 : this.getDeptParent().hashCode());
		result = 37 * result + (getDesc() == null ? 0 : this.getDesc().hashCode());
		result = 37 * result + (getEnable() == null ? 0 : this.getEnable().hashCode());
		return result;
	}

}
