package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * EmpJobbing generated by hbm2java
 */
public class EmpJobbing implements java.io.Serializable {

	private String id;
	private String empId;
	private int joinType;
	private String fromCor;
	private String project;
	private Date joinDate;
	private String urgent;

	public EmpJobbing() {
	}

	public EmpJobbing(String id, String empId, int joinType) {
		this.id = id;
		this.empId = empId;
		this.joinType = joinType;
	}

	public EmpJobbing(String id, String empId, int joinType, String fromCor, String project, Date joinDate,
			String urgent) {
		this.id = id;
		this.empId = empId;
		this.joinType = joinType;
		this.fromCor = fromCor;
		this.project = project;
		this.joinDate = joinDate;
		this.urgent = urgent;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public int getJoinType() {
		return this.joinType;
	}

	public void setJoinType(int joinType) {
		this.joinType = joinType;
	}

	public String getFromCor() {
		return this.fromCor;
	}

	public void setFromCor(String fromCor) {
		this.fromCor = fromCor;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public String getUrgent() {
		return this.urgent;
	}

	public void setUrgent(String urgent) {
		this.urgent = urgent;
	}

}
