package com.iss.db.bean;
// Generated 2017-3-2 10:35:41 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * Employeepaymentview generated by hbm2java
 */
public class Employeepaymentview implements java.io.Serializable {

	private String id;
	private String empid;
	private String nameCn;
	private String sex;
	private long deptId;
	private String deptName;
	private long jobId;
	private String jobTitle;
	private String empno;
	private BigDecimal base;
	private BigDecimal job;
	private BigDecimal traffic;
	private BigDecimal communicate;
	private BigDecimal trip;
	private BigDecimal endowment;
	private BigDecimal medical;
	private BigDecimal unemployment;
	private BigDecimal pafhc;

	public Employeepaymentview() {
	}

	public Employeepaymentview(String id, String empid, String nameCn, String sex, long deptId, String deptName,
			long jobId, String jobTitle, String empno, BigDecimal base, BigDecimal job, BigDecimal traffic,
			BigDecimal communicate, BigDecimal trip, BigDecimal endowment, BigDecimal medical, BigDecimal unemployment,
			BigDecimal pafhc) {
		this.id = id;
		this.empid = empid;
		this.nameCn = nameCn;
		this.sex = sex;
		this.deptId = deptId;
		this.deptName = deptName;
		this.jobId = jobId;
		this.jobTitle = jobTitle;
		this.empno = empno;
		this.base = base;
		this.job = job;
		this.traffic = traffic;
		this.communicate = communicate;
		this.trip = trip;
		this.endowment = endowment;
		this.medical = medical;
		this.unemployment = unemployment;
		this.pafhc = pafhc;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmpid() {
		return this.empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(long deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public String getEmpno() {
		return this.empno;
	}

	public void setEmpno(String empno) {
		this.empno = empno;
	}

	public BigDecimal getBase() {
		return this.base;
	}

	public void setBase(BigDecimal base) {
		this.base = base;
	}

	public BigDecimal getJob() {
		return this.job;
	}

	public void setJob(BigDecimal job) {
		this.job = job;
	}

	public BigDecimal getTraffic() {
		return this.traffic;
	}

	public void setTraffic(BigDecimal traffic) {
		this.traffic = traffic;
	}

	public BigDecimal getCommunicate() {
		return this.communicate;
	}

	public void setCommunicate(BigDecimal communicate) {
		this.communicate = communicate;
	}

	public BigDecimal getTrip() {
		return this.trip;
	}

	public void setTrip(BigDecimal trip) {
		this.trip = trip;
	}

	public BigDecimal getEndowment() {
		return this.endowment;
	}

	public void setEndowment(BigDecimal endowment) {
		this.endowment = endowment;
	}

	public BigDecimal getMedical() {
		return this.medical;
	}

	public void setMedical(BigDecimal medical) {
		this.medical = medical;
	}

	public BigDecimal getUnemployment() {
		return this.unemployment;
	}

	public void setUnemployment(BigDecimal unemployment) {
		this.unemployment = unemployment;
	}

	public BigDecimal getPafhc() {
		return this.pafhc;
	}

	public void setPafhc(BigDecimal pafhc) {
		this.pafhc = pafhc;
	}

}
