package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * EmpNormal generated by hbm2java
 */
public class EmpNormal implements java.io.Serializable {

	private String id;
	private String empId;
	private String eduHistory;
	private Date joinDate;
	private String jobCertify;
	private String bank;
	private String bankNo;

	public EmpNormal() {
	}

	public EmpNormal(String id, String empId, String eduHistory) {
		this.id = id;
		this.empId = empId;
		this.eduHistory = eduHistory;
	}

	public EmpNormal(String id, String empId, String eduHistory, Date joinDate, String jobCertify, String bank,
			String bankNo) {
		this.id = id;
		this.empId = empId;
		this.eduHistory = eduHistory;
		this.joinDate = joinDate;
		this.jobCertify = jobCertify;
		this.bank = bank;
		this.bankNo = bankNo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getEduHistory() {
		return this.eduHistory;
	}

	public void setEduHistory(String eduHistory) {
		this.eduHistory = eduHistory;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public String getJobCertify() {
		return this.jobCertify;
	}

	public void setJobCertify(String jobCertify) {
		this.jobCertify = jobCertify;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

}
