package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Jobbingemployeeview generated by hbm2java
 */
public class Jobbingemployeeview implements java.io.Serializable {

	private String id;

	public Jobbingemployeeview() {
	}

	public Jobbingemployeeview(String id) {
		this.id = id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String string) {
		this.id = string;
	}

	public String getEmpNo() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getNameCn() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getBank() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setEmpNo(String empNo) {
		// TODO Auto-generated method stub
		
	}

	public void setNameCn(String nameCn) {
		// TODO Auto-generated method stub
		
	}


}
