package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Jobview generated by hbm2java
 */
public class Jobview implements java.io.Serializable {

	private JobviewId id;

	public Jobview() {
	}

	public Jobview(JobviewId id) {
		this.id = id;
	}

	public JobviewId getId() {
		return this.id;
	}

	public void setId(JobviewId id) {
		this.id = id;
	}

}
