package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * JobviewId generated by hbm2java
 */
public class JobviewId implements java.io.Serializable {

	private int id;
	private String jobTitle;
	private Integer reportTo;
	private String jobParent;
	private String desc;
	private Byte enable;

	public JobviewId() {
	}

	public JobviewId(int id, String jobTitle) {
		this.id = id;
		this.jobTitle = jobTitle;
	}

	public JobviewId(int id, String jobTitle, Integer reportTo, String jobParent, String desc, Byte enable) {
		this.id = id;
		this.jobTitle = jobTitle;
		this.reportTo = reportTo;
		this.jobParent = jobParent;
		this.desc = desc;
		this.enable = enable;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Integer getReportTo() {
		return this.reportTo;
	}

	public void setReportTo(Integer reportTo) {
		this.reportTo = reportTo;
	}

	public String getJobParent() {
		return this.jobParent;
	}

	public void setJobParent(String jobParent) {
		this.jobParent = jobParent;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Byte getEnable() {
		return this.enable;
	}

	public void setEnable(Byte enable) {
		this.enable = enable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobviewId))
			return false;
		JobviewId castOther = (JobviewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getJobTitle() == castOther.getJobTitle()) || (this.getJobTitle() != null
						&& castOther.getJobTitle() != null && this.getJobTitle().equals(castOther.getJobTitle())))
				&& ((this.getReportTo() == castOther.getReportTo()) || (this.getReportTo() != null
						&& castOther.getReportTo() != null && this.getReportTo().equals(castOther.getReportTo())))
				&& ((this.getJobParent() == castOther.getJobParent()) || (this.getJobParent() != null
						&& castOther.getJobParent() != null && this.getJobParent().equals(castOther.getJobParent())))
				&& ((this.getDesc() == castOther.getDesc()) || (this.getDesc() != null && castOther.getDesc() != null
						&& this.getDesc().equals(castOther.getDesc())))
				&& ((this.getEnable() == castOther.getEnable()) || (this.getEnable() != null
						&& castOther.getEnable() != null && this.getEnable().equals(castOther.getEnable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getJobTitle() == null ? 0 : this.getJobTitle().hashCode());
		result = 37 * result + (getReportTo() == null ? 0 : this.getReportTo().hashCode());
		result = 37 * result + (getJobParent() == null ? 0 : this.getJobParent().hashCode());
		result = 37 * result + (getDesc() == null ? 0 : this.getDesc().hashCode());
		result = 37 * result + (getEnable() == null ? 0 : this.getEnable().hashCode());
		return result;
	}

}
