package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Normalemployeeview generated by hbm2java
 */
public class Normalemployeeview implements java.io.Serializable {

	private NormalemployeeviewId id;

	public Normalemployeeview() {
	}

	public Normalemployeeview(NormalemployeeviewId id) {
		this.id = id;
	}

	public NormalemployeeviewId getId() {
		return this.id;
	}

	public void setId(NormalemployeeviewId id) {
		this.id = id;
	}

	public String getEmpNo() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getNameCn() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getBank() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getTel() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setNameCn(String nameCn) {
		// TODO Auto-generated method stub
		
	}

	public void setEmpNo(String empNo) {
		// TODO Auto-generated method stub
		
	}

	public void setTel(String tel) {
		// TODO Auto-generated method stub
		
	}

	public void setBank(String bank) {
		// TODO Auto-generated method stub
		
	}

}
