package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Outeremployeeview generated by hbm2java
 */
public class Outeremployeeview implements java.io.Serializable {

	private OuteremployeeviewId id;

	public Outeremployeeview() {
	}

	public Outeremployeeview(OuteremployeeviewId id) {
		this.id = id;
	}

	public OuteremployeeviewId getId() {
		return this.id;
	}

	public void setId(OuteremployeeviewId id) {
		this.id = id;
	}

}
