package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Arrays;

/**
 * OuteremployeeviewId generated by hbm2java
 */
public class OuteremployeeviewId implements java.io.Serializable {

	private String id;
	private String empNo;
	private String nameCn;
	private String sex;
	private String birth;
	private String personId;
	private String tel;
	private String qq;
	private String email;
	private String country;
	private int state;
	private long deptId;
	private long jobId;
	private String oid;
	private String sendCor;
	private String sendBegin;
	private String sendContract;
	private BigDecimal cycle;
	private byte[] subsidy;

	public OuteremployeeviewId() {
	}

	public OuteremployeeviewId(String id, String empNo, String nameCn, String sex, String birth, String personId,
			String tel, String qq, String email, int state, long deptId, long jobId, String oid, String sendCor,
			String sendBegin, String sendContract, BigDecimal cycle, byte[] subsidy) {
		this.id = id;
		this.empNo = empNo;
		this.nameCn = nameCn;
		this.sex = sex;
		this.birth = birth;
		this.personId = personId;
		this.tel = tel;
		this.qq = qq;
		this.email = email;
		this.state = state;
		this.deptId = deptId;
		this.jobId = jobId;
		this.oid = oid;
		this.sendCor = sendCor;
		this.sendBegin = sendBegin;
		this.sendContract = sendContract;
		this.cycle = cycle;
		this.subsidy = subsidy;
	}

	public OuteremployeeviewId(String id, String empNo, String nameCn, String sex, String birth, String personId,
			String tel, String qq, String email, String country, int state, long deptId, long jobId, String oid,
			String sendCor, String sendBegin, String sendContract, BigDecimal cycle, byte[] subsidy) {
		this.id = id;
		this.empNo = empNo;
		this.nameCn = nameCn;
		this.sex = sex;
		this.birth = birth;
		this.personId = personId;
		this.tel = tel;
		this.qq = qq;
		this.email = email;
		this.country = country;
		this.state = state;
		this.deptId = deptId;
		this.jobId = jobId;
		this.oid = oid;
		this.sendCor = sendCor;
		this.sendBegin = sendBegin;
		this.sendContract = sendContract;
		this.cycle = cycle;
		this.subsidy = subsidy;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getBirth() {
		return this.birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(long deptId) {
		this.deptId = deptId;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getSendCor() {
		return this.sendCor;
	}

	public void setSendCor(String sendCor) {
		this.sendCor = sendCor;
	}

	public String getSendBegin() {
		return this.sendBegin;
	}

	public void setSendBegin(String sendBegin) {
		this.sendBegin = sendBegin;
	}

	public String getSendContract() {
		return this.sendContract;
	}

	public void setSendContract(String sendContract) {
		this.sendContract = sendContract;
	}

	public BigDecimal getCycle() {
		return this.cycle;
	}

	public void setCycle(BigDecimal cycle) {
		this.cycle = cycle;
	}

	public byte[] getSubsidy() {
		return this.subsidy;
	}

	public void setSubsidy(byte[] subsidy) {
		this.subsidy = subsidy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OuteremployeeviewId))
			return false;
		OuteremployeeviewId castOther = (OuteremployeeviewId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getEmpNo() == castOther.getEmpNo()) || (this.getEmpNo() != null
						&& castOther.getEmpNo() != null && this.getEmpNo().equals(castOther.getEmpNo())))
				&& ((this.getNameCn() == castOther.getNameCn()) || (this.getNameCn() != null
						&& castOther.getNameCn() != null && this.getNameCn().equals(castOther.getNameCn())))
				&& ((this.getSex() == castOther.getSex()) || (this.getSex() != null && castOther.getSex() != null
						&& this.getSex().equals(castOther.getSex())))
				&& ((this.getBirth() == castOther.getBirth()) || (this.getBirth() != null
						&& castOther.getBirth() != null && this.getBirth().equals(castOther.getBirth())))
				&& ((this.getPersonId() == castOther.getPersonId()) || (this.getPersonId() != null
						&& castOther.getPersonId() != null && this.getPersonId().equals(castOther.getPersonId())))
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null && castOther.getTel() != null
						&& this.getTel().equals(castOther.getTel())))
				&& ((this.getQq() == castOther.getQq()) || (this.getQq() != null && castOther.getQq() != null
						&& this.getQq().equals(castOther.getQq())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& (this.getState() == castOther.getState()) && (this.getDeptId() == castOther.getDeptId())
				&& (this.getJobId() == castOther.getJobId())
				&& ((this.getOid() == castOther.getOid()) || (this.getOid() != null && castOther.getOid() != null
						&& this.getOid().equals(castOther.getOid())))
				&& ((this.getSendCor() == castOther.getSendCor()) || (this.getSendCor() != null
						&& castOther.getSendCor() != null && this.getSendCor().equals(castOther.getSendCor())))
				&& ((this.getSendBegin() == castOther.getSendBegin()) || (this.getSendBegin() != null
						&& castOther.getSendBegin() != null && this.getSendBegin().equals(castOther.getSendBegin())))
				&& ((this.getSendContract() == castOther.getSendContract())
						|| (this.getSendContract() != null && castOther.getSendContract() != null
								&& this.getSendContract().equals(castOther.getSendContract())))
				&& ((this.getCycle() == castOther.getCycle()) || (this.getCycle() != null
						&& castOther.getCycle() != null && this.getCycle().equals(castOther.getCycle())))
				&& ((this.getSubsidy() == castOther.getSubsidy()) || (this.getSubsidy() != null
						&& castOther.getSubsidy() != null && Arrays.equals(this.getSubsidy(), castOther.getSubsidy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getEmpNo() == null ? 0 : this.getEmpNo().hashCode());
		result = 37 * result + (getNameCn() == null ? 0 : this.getNameCn().hashCode());
		result = 37 * result + (getSex() == null ? 0 : this.getSex().hashCode());
		result = 37 * result + (getBirth() == null ? 0 : this.getBirth().hashCode());
		result = 37 * result + (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result + (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result + (getQq() == null ? 0 : this.getQq().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + this.getState();
		result = 37 * result + (int) this.getDeptId();
		result = 37 * result + (int) this.getJobId();
		result = 37 * result + (getOid() == null ? 0 : this.getOid().hashCode());
		result = 37 * result + (getSendCor() == null ? 0 : this.getSendCor().hashCode());
		result = 37 * result + (getSendBegin() == null ? 0 : this.getSendBegin().hashCode());
		result = 37 * result + (getSendContract() == null ? 0 : this.getSendContract().hashCode());
		result = 37 * result + (getCycle() == null ? 0 : this.getCycle().hashCode());
		int subsidyHashcode = 0;
		byte[] subsidyProperty = this.getSubsidy();
		if (subsidyProperty != null) {
			subsidyHashcode = 1;
			for (int i = 0; i < subsidyProperty.length; i++) {
				subsidyHashcode = 37 * subsidyHashcode + subsidyProperty[i];
			}
		}

		result = 37 * result + subsidyHashcode;

		return result;
	}

}
