package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private String id;
	private String empId;
	private BigDecimal base;
	private BigDecimal job;
	private BigDecimal traffic;
	private BigDecimal communicate;
	private BigDecimal trip;
	private BigDecimal endowment;
	private BigDecimal medical;
	private BigDecimal unemployment;
	private BigDecimal pafhc;

	public Payment() {
	}

	public Payment(String id, String empId) {
		this.id = id;
		this.empId = empId;
	}

	public Payment(String id, String empId, BigDecimal base, BigDecimal job, BigDecimal traffic, BigDecimal communicate,
			BigDecimal trip, BigDecimal endowment, BigDecimal medical, BigDecimal unemployment, BigDecimal pafhc) {
		this.id = id;
		this.empId = empId;
		this.base = base;
		this.job = job;
		this.traffic = traffic;
		this.communicate = communicate;
		this.trip = trip;
		this.endowment = endowment;
		this.medical = medical;
		this.unemployment = unemployment;
		this.pafhc = pafhc;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public BigDecimal getBase() {
		return this.base;
	}

	public void setBase(BigDecimal base) {
		this.base = base;
	}

	public BigDecimal getJob() {
		return this.job;
	}

	public void setJob(BigDecimal job) {
		this.job = job;
	}

	public BigDecimal getTraffic() {
		return this.traffic;
	}

	public void setTraffic(BigDecimal traffic) {
		this.traffic = traffic;
	}

	public BigDecimal getCommunicate() {
		return this.communicate;
	}

	public void setCommunicate(BigDecimal communicate) {
		this.communicate = communicate;
	}

	public BigDecimal getTrip() {
		return this.trip;
	}

	public void setTrip(BigDecimal trip) {
		this.trip = trip;
	}

	public BigDecimal getEndowment() {
		return this.endowment;
	}

	public void setEndowment(BigDecimal endowment) {
		this.endowment = endowment;
	}

	public BigDecimal getMedical() {
		return this.medical;
	}

	public void setMedical(BigDecimal medical) {
		this.medical = medical;
	}

	public BigDecimal getUnemployment() {
		return this.unemployment;
	}

	public void setUnemployment(BigDecimal unemployment) {
		this.unemployment = unemployment;
	}

	public BigDecimal getPafhc() {
		return this.pafhc;
	}

	public void setPafhc(BigDecimal pafhc) {
		this.pafhc = pafhc;
	}

}
