package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Rolelist generated by hbm2java
 */
public class Rolelist implements java.io.Serializable {

	private String role;

	public Rolelist() {
	}

	public Rolelist(String role) {
		this.role = role;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
