package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Studentemployeeview generated by hbm2java
 */
public class Studentemployeeview implements java.io.Serializable {

	private StudentemployeeviewId id;

	public Studentemployeeview() {
	}

	public Studentemployeeview(StudentemployeeviewId id) {
		this.id = id;
	}

	public StudentemployeeviewId getId() {
		return this.id;
	}

	public void setId(StudentemployeeviewId id) {
		this.id = id;
	}

}
