package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Sysdictvalue generated by hbm2java
 */
public class Sysdictvalue implements java.io.Serializable {

	private Integer id;
	private int typeid;
	private String value;
	private String show;
	private String desc;
	private Byte enable;

	public Sysdictvalue() {
	}

	public Sysdictvalue(int typeid, String value, String show) {
		this.typeid = typeid;
		this.value = value;
		this.show = show;
	}

	public Sysdictvalue(int typeid, String value, String show, String desc, Byte enable) {
		this.typeid = typeid;
		this.value = value;
		this.show = show;
		this.desc = desc;
		this.enable = enable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTypeid() {
		return this.typeid;
	}

	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getShow() {
		return this.show;
	}

	public void setShow(String show) {
		this.show = show;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Byte getEnable() {
		return this.enable;
	}

	public void setEnable(Byte enable) {
		this.enable = enable;
	}

}
