package com.iss.db.bean;
// Generated 2017-3-8 16:19:15 by Hibernate Tools 4.3.5.Final

/**
 * Sysuser generated by hbm2java
 */
public class Sysuser implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String pwd;
	private String displayname;
	private String desc;
	private Byte enable;
	private String role;

	public Sysuser() {
	}

	public Sysuser(String uid, String pwd) {
		this.uid = uid;
		this.pwd = pwd;
	}

	public Sysuser(String uid, String pwd, String displayname, String desc, Byte enable, String role) {
		this.uid = uid;
		this.pwd = pwd;
		this.displayname = displayname;
		this.desc = desc;
		this.enable = enable;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Byte getEnable() {
		return this.enable;
	}

	public void setEnable(Byte enable) {
		this.enable = enable;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
